### ISSUE TITLE
Analyzer error

### ISSUE THREAD

**Issue by hoangvu304** [bitkeks/python-netflow-v9-softflowd#17]
Hi @bitkeks ,
Thank for your app. I try it today, capture some packet from a ASR 1002 router netflow v9 export.
But when I analyzer .gz file, it's show error:
(p3venv) [vuht@dashboard python-netflow-v9-softflowd]$ python analyzer.py -f 1581912445.gz 
Traceback (most recent call last):
  File "analyzer.py", line 215, in <module>
    for flow in sorted(flows, key=lambda x: x["FIRST_SWITCHED"]):
  File "analyzer.py", line 215, in <lambda>
    for flow in sorted(flows, key=lambda x: x["FIRST_SWITCHED"]):
KeyError: 'FIRST_SWITCHED'

**Comment by bitkeks** [comment]
Hi @hoangvu304,
sorry for the long delay! Do you still have your capture file? I'd be interested in seeing, which fields are actually contained in your exports. You could try to add a `print(flows[0])` in line 242 https://github.com/bitkeks/python-netflow-v9-softflowd/blob/f8c5717002c431fbda9189713d038d2d9be7ccac/analyzer.py#L241-L243
This might reveal the fields. Sadly, the [docs on the ASR 1002](https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/netflow/configuration/xe-16/nf-xe-16-book.html) do not state which fields are exported, but maybe we can figure out if there's another field that has the same effect (timestamp).
Or did you use "Flexible Netflow"? This seems to be an newer, extended NetFlow v9 implementation by Cisco which is configured differently.
