### ISSUE TITLE
analyze_json.py - error

### ISSUE THREAD

**Issue by xssec** [bitkeks/python-netflow-v9-softflowd#5]
Hi,

Could you please to fix this issue?

```
python3 analyze_json.py 1534395555.json 
Traceback (most recent call last):
  File "analyze_json.py", line 127, in <module>
    data = json.loads(fh.read())
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by xssec** [comment]
Hi, 

Thank you for your help, attached the json file.
[1534402953.zip](https://github.com/bitkeks/python-netflow-v9-softflowd/files/2293364/1534402953.zip)

**Comment by xssec** [comment]
Hi,

Is there any update?

**Comment by bitkeks** [comment]
Did you try to analyse the `1534402953.json`? Your two JSON files are not the same, so the error is not directly reproducable. I still think your first mentioned file was simply empty, because of a script restart or similar. The collector has a delay in which it has to receive flows from the source. Until then, nothing is written into the JSON file. 

`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` is an error occuring if an empty file is passed into JSON.decode.

**Comment by xssec** [comment]
Hi,

There are some error again,

/opt/python-netflow-v9-softflowd# python3 main.py -p 9009 -D
Listening on interface :9009
Starting the NetFlow listener
Received data from 103.56.234.9, length 1392
----------------------------------------
Exception happened during processing of request from ('103.56.234.9', 3464)
Traceback (most recent call last):
 File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
   self.process_request(request, client_address)
 File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
   self.finish_request(request, client_address)
 File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
   self.RequestHandlerClass(request, client_address, self)
 File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
   self.handle()
 File "main.py", line 72, in handle
   export = ExportPacket(data, self.TEMPLATES)
 File "/usr/local/lib/python3.5/dist-packages/netflow_v9-0.6.1-py3.5.egg/netflow/collector_v9.py", line 316, in __init__
   dfs = DataFlowSet(data[offset:], self.templates)
 File "/usr/local/lib/python3.5/dist-packages/netflow_v9-0.6.1-py3.5.egg/netflow/collector_v9.py", line 184, in __init__
   template = templates[self.template_id]
KeyError: 260
----------------------------------------

**Comment by bitkeks** [comment]
The souce of error `template = templates[self.template_id] -> KeyError: 260` comes from unknown templates. See #4 for more details. Hope to resolve this issue in one of the next updates!
